FROM python:3.12-slim
WORKDIR /app
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 OBSERVER_MODE=model OBSERVER_SCHEDULER=window-search SAC_OPPORTUNITY_LOOKAHEAD=1 MODEL_PROVIDER=none SAC_FORMAL_SEARCH=off SAC_WINDOW_HORIZON=7200 SAC_WINDOW_WIDTH=32 SAC_WINDOW_BUDGET=50000 SAC_WINDOW_TAIL=threshold SAC_WINDOW_WEATHER=0.5 SAC_WINDOW_FORECAST=1 MODEL_NAME=deepseek-flash MODEL_BASE_URL=https://api.deepseek.com MODEL_API_MODE=chat MODEL_API_KEY_ENV=MODEL_API_KEY MODEL_REASONING_EFFORT=low OBSERVER_PLAN_GUARD=1 OBSERVER_OFFLINE_PORTFOLIO=0 OBSERVER_GUARD_MARGIN=0.02 OBSERVER_MODEL_TIMEOUT=60 OBSERVER_MAX_MODEL_CALLS=16 OBSERVER_MAX_OUTPUT_TOKENS=4096
COPY agent/ /app/agent/
COPY run_agent.py settings.json /app/
RUN useradd --create-home --uid 10001 observer
USER observer
ENTRYPOINT ["python", "-I", "-u", "/app/run_agent.py"]
